#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

rm -rf $HOME/Brewfile
ln -s $DOTFILES/Brewfile $HOME/Brewfile

brew bundle

rm -rf $HOME/.zshrc
ln -s $DOTFILES/zsh/zsh.conf $HOME/.zshrc

rm -rf $HOME/.config/nvim
mkdir -p $HOME/.config
ln -s $DOTFILES/nvim $HOME/.config

rm -rf $HOME/.tmux.conf
ln -s $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

rm -rf $HOME/.local/bin
mkdir -p $HOME/.local/bin

ln -s $DOTFILES/scripts/* $HOME/.local/bin
