#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

# rm -rf $HOME/Brewfile
# ln -s $DOTFILES/Brewfile $HOME/Brewfile

# brew bundle

rm -rf $HOME/.zshrc
ln -s $DOTFILES/zsh/zsh.conf $HOME/.zshrc

rm -rf $HOME/.config/nvim
mkdir -p $HOME/.config
ln -s $DOTFILES/nvim $HOME/.config

rm -rf $HOME/.tmux.conf
rm -rf $HOME/.config/tmux
mkdir -p $HOME/.config
ln -s $DOTFILES/tmux $HOME/.config

rm -rf $HOME/bin
mkdir -p $HOME/bin
ln -s $DOTFILES/scripts/* $HOME/bin

rm -rf $HOME/.wezterm.lua
ln -s $DOTFILES/wezterm/config.lua $HOME/.wezterm.lua
