set -g default-terminal "xterm-256color"

unbind C-b
set -g prefix C-Space

unbind r
bind r source-file ~/.tmux.conf \; display "Reloaded ~/.tmux.conf"

# resize panes
bind -r h resize-pane -L 5
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5

# switch panes
bind-key -n C-h select-pane -L
bind-key -n C-j select-pane -D
bind-key -n C-k select-pane -U
bind-key -n C-l select-pane -R

### COLORS
# default statusbar colors
set-option -g status-style fg=yellow,bg=black

# default window title colors
set-window-option -g window-status-style fg=brightblue,bg=default

# active window title colors
set-window-option -g window-status-current-style fg=brightred,bg=default

# pane border
set-option -g pane-border-style fg=black
set-option -g pane-active-border-style fg=brightgreen

#message text
set-option -g message-style fg=brightred,bg=black

# pane number display
set-option -g display-panes-active-colour blue
set-option -g display-panes-colour brightred

# clock
set-window-option -g clock-mode-colour green

# bell 
set-window-option -g window-status-bell-style fg=black,bg=red
### END COLOR

#
# Plugins
#
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/vim-tmux-navigator'

run -b '~/.tmux/plugins/tpm/tpm'
