#!/usr/bin/env bash

# Credit to TheWintergen

if [[ $# -eq 1 ]]; then
    selected=$1
else
    items=`tmux list-sessions -F "#S"`
    selected=`echo "$items" | fzf`
fi

tmux switch-client -t =$selected
if [[ $? -eq 0 ]]; then
    exit 0
fi

tmux new-session -c $selected -d -s $dirname && tmux switch-client -t $dirname || tmux new -c $selected -A -s $dirname
