COMPOSER_MEMORY_LIMIT=-1

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH
# export PATH="/usr/local/Cellar/mysql@5.7/5.7.29/bin:$PATH"
# export PATH="$HOME/Downloads/ngrok:$PATH"
# export PATH="/usr/local/opt/php@8.0/bin:$PATH"
# export PATH="/usr/local/opt/php@8.0/sbin:$PATH"

# gb
# export PATH="/usr/local/opt/php@7.4/bin:$PATH"
# export PATH="/opt/homebrew/opt/php@7.4/sbin:$PATH"
# export PATH="$HOME/.composer/vendor/bin:$PATH"

export ZSH=$HOME/.oh-my-zsh

ZSH_THEME=robbyrussell
#
ZSH_CUSTOM=$HOME/etc/zsh

plugins=(git zsh-syntax-highlighting git-trim)

source $ZSH/oh-my-zsh.sh

export EDITOR='nvim'

# Filesystem
eval "$(/opt/homebrew/bin/brew shellenv)"

# fnm
export PATH=$HOME/.fnm:$PATH
eval "$(fnm env)"

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# editor
alias vim="nvim"
alias v="vim"

# config shortcuts
alias vimconfig="v ~/.config/nvim/init.vim"
alias tmuxconfig="v ~/.tmux.conf"
alias zshconfig="vim ~/.zshrc"
alias zshreload="source ~/.zshrc"

# Laravel
alias art="php artisan"
alias tinker="php artisan tinker"

# Composer
alias c="composer"
alias ci="composer install"
alias cr="composer require"
alias cu="composer update"
alias ct="composer test"
alias cda="composer dump-autoload"
alias cino="composer install --ignore-platform-reqs"

# git
alias nah="git reset --hard && git clean -df"
alias gs="git status"
alias ga="git add -A"
alias gc="git commit"
alias gch="git checkout"
alias gp="git push origin master"
alias gpl="git pull"
alias gl="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias gt="git trim --pruned --merged"
alias gmy='git log --all --author="Clint Winter"'

# TODO: move these into an optional per-device file
# ngrok
alias ngrokgb="ngrok http -subdomain=clint -host-header=givebutter.test 443"
alias ngrokapi="ngrok http -subdomain=clint api.givebutter.test 443"

# aliases for various ssh servers
alias ssh-friiworld="ssh -i $HOME/Documents/codementor/nabeel/London.pem bitnami@18.168.247.46"
